name: Sync with upstream repository

# 触发条件：定期运行和手动触发
on:
  schedule:
    # 每天凌晨2点运行（UTC时间）
    - cron: '0 2 * * *'
  workflow_dispatch:
    # 允许手动触发工作流
    inputs:
      branch:
        description: 'Branch to sync (default: main)'
        required: false
        default: 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录
          token: ${{ secrets.GITHUB_TOKEN }}

      # 配置Git用户信息
      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # 添加上游仓库
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/factoriolab/factoriolab.git
          git fetch upstream

      # 合并上游更新
      - name: Merge upstream changes
        run: |
          BRANCH=${{ github.event.inputs.branch || 'main' }}
          git checkout $BRANCH
          git merge --no-edit upstream/$BRANCH

      # 推送更新到用户的fork仓库
      - name: Push changes to fork
        run: |
          BRANCH=${{ github.event.inputs.branch || 'main' }}
          git push origin $BRANCH

      # 克隆factoriolab-File仓库以获取配置文件
      - name: Clone factoriolab-File repository
        run: |
          # 使用GitHub Token克隆factoriolab-File仓库（确保该仓库已公开或可通过GITHUB_TOKEN访问）
          git clone https://github.com:dkfghrdso/factoriolab-File.git temp-file-repo
          cd temp-file-repo
          ls -la

      # 复制配置文件到正确位置
      - name: Copy configuration files
        run: |
          # 复制src目录下的配置文件
          cp -f temp-file-repo/_redirects src/_redirects
          cp -f temp-file-repo/_headers src/_headers
          
          # 复制根目录下的配置文件
          cp -f temp-file-repo/cloudflare.config.js ./cloudflare.config.js
          
          # 检查配置文件是否成功复制
          ls -la src/_redirects src/_headers cloudflare.config.js

      # 检查并更新angular.json（确保配置文件被包含在构建中）
      - name: Check and update angular.json
        run: |
          # 检查_redirects是否已在angular.json中
          if ! grep -q "src/_redirects" angular.json; then
            echo "Adding src/_redirects to angular.json"
            # 使用jq工具添加_redirects配置（如果已安装）
            if command -v jq &> /dev/null; then
              jq '.projects["factoriolab"].architect.build.options.assets += ["src/_redirects"]' angular.json > angular.json.tmp
              mv angular.json.tmp angular.json
            fi
          fi
          
          # 检查_headers是否已在angular.json中
          if ! grep -q "src/_headers" angular.json; then
            echo "Adding src/_headers to angular.json"
            # 使用jq工具添加_headers配置（如果已安装）
            if command -v jq &> /dev/null; then
              jq '.projects["factoriolab"].architect.build.options.assets += ["src/_headers"]' angular.json > angular.json.tmp
              mv angular.json.tmp angular.json
            fi
          fi

      # 提交配置文件更改
      - name: Commit configuration files
        run: |
          BRANCH=${{ github.event.inputs.branch || 'main' }}
          git add src/_redirects src/_headers cloudflare.config.js angular.json
          git commit -m "Update Cloudflare Pages configuration files"
          git push origin $BRANCH